version: 2

build:
  os: ubuntu-20.04
  tools:
    python: "3.8"
  jobs:
    pre_build:
      # Turn off notebook execution (will use saved '*_doc.ipynb' files)
      - "idaesx conf --execute off"

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - dev

sphinx:
  builder: html
  fail_on_warning: false