version: 2

build:
  os: ubuntu-20.04
  tools:
    python: "3.10"
  jobs:
    pre_build:
      # Set conf vars and  update the Sphinx configuration (conf.py)
      - idaesx conf --execute off --sphinx --show
python:
  install:
    - requirements: requirements-dev.txt

sphinx:
  builder: html
  fail_on_warning: false
  configuration: idaes_examples/notebooks/conf.py

