version: 2

build:
  os: ubuntu-20.04
  tools:
    python: "3.8"
  jobs:
    pre_build:
      # Create the _doc notebooks
      - idaesx pre -v
      # Turn off notebook execution (will use saved '*_doc.ipynb' files)
      - idaesx conf -v --execute cache --timeout 600
      - idaesx conf
python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - jb

sphinx:
  builder: html
  fail_on_warning: false