version: 2

build:
  os: ubuntu-20.04
  tools:
    python: "3.8"
  jobs:
    pre_build:
      # Create the _doc notebooks
      - idaesx pre -v
      # Use cached data instead of notebook execution (will use saved '*_doc.ipynb' files)
      # This also updates the Sphinx configuration (conf.py)
      - idaesx conf --execute cache --timeout 600 --sphinx --show
python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - jb

sphinx:
  builder: html
  fail_on_warning: false