version: 2

build:
  os: ubuntu-20.04
  tools:
    python: "3.8"
  jobs:
    pre_build:
      # Generate variations on the base notebook files, in particular one for docs.
      - "idaesx pre"
      # Generate the Sphinx configuration for this Jupyter Book, so it builds.
      - "jupyter-book config sphinx idaes_examples/notebooks/"
      # Install IDAES extensions
      - "idaes get-extensions --extra petsc --verbose"

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - dev

sphinx:
  builder: html
  fail_on_warning: false